### ISSUE TITLE
EntryPoint for SetConsoleCtrlHandler 

### ISSUE THREAD

**Issue by rqx110** [kkwpsv/lsjutil#4]
https://github.com/kkwpsv/lsjutil/blob/53d6b8c13d9bbb74495c5da6ac579a74ebaec9ff/Src/Lsj.Util.Win32/Kernel32.Console.cs#L848

the EntryPoint for SetConsoleCtrlHandler here should be `SetConsoleCtrlHandler`?

**Comment by kkwpsv** [comment]
yes, that's my mistake. I'll fix it.

**Comment by kkwpsv** [comment]
4b69f1ac465b61081e13c1f844d7fc8f929637ea
